version: "3.4"

services:
  server_a:
    build:
      context: ..
      target: development
    working_dir: /app/application
    command: bash -c "gcloud auth activate-service-account --key-file /app/.credentials && bin/process.sh"
    volumes:
      - .:/app/application
      - ~/gcp-service-credentials/priotest-a-prod-dc20730c9063.json:/app/.credentials
    environment:
      - N_DATA=3
      - BATCH_ID=test
      - SERVER_ID=A
      - SHARED_SECRET=m/AqDal/ZSA9597GwMM+VA==
      - PRIVATE_KEY_HEX=19DDC146FB8EE4A0B762A7DAE7E96033F87C9528DBBF8CA899CCD1DB8CD74984
      - PUBLIC_KEY_HEX_INTERNAL=445C126981113E5684D517826E508F5731A1B35485BACCD63DAA8120DD11DA78
      - PUBLIC_KEY_HEX_EXTERNAL=01D5D4F179ED233140CF97F79594F0190528268A99A6CDF57EF0E1569E673642
      - BUCKET_INTERNAL_PRIVATE=project-a-private
      - BUCKET_INTERNAL_SHARED=project-a-shared
      - BUCKET_EXTERNAL_SHARED=project-b-shared
  server_b:
    build:
      context: ..
      target: development
    working_dir: /app/application
    command: bash -c "gcloud auth activate-service-account --key-file /app/.credentials && bin/process.sh"
    volumes:
      - .:/app/application
      - ~/gcp-service-credentials/priotest-b-prod-93cef8d90cb6.json:/app/.credentials
    environment:
      - N_DATA=3
      - BATCH_ID=test
      - SERVER_ID=B
      - SHARED_SECRET=m/AqDal/ZSA9597GwMM+VA==
      - PRIVATE_KEY_HEX=E3AA3CC952C8553E46E699646A9DC3CBA7E3D4C7F0779D58574ABF945E259202
      - PUBLIC_KEY_HEX_INTERNAL=01D5D4F179ED233140CF97F79594F0190528268A99A6CDF57EF0E1569E673642
      - PUBLIC_KEY_HEX_EXTERNAL=445C126981113E5684D517826E508F5731A1B35485BACCD63DAA8120DD11DA78
      - BUCKET_INTERNAL_PRIVATE=project-b-private
      - BUCKET_INTERNAL_SHARED=server-b-shared
      - BUCKET_EXTERNAL_SHARED=server-a-shared
