version: '3.4'

x-app: &app
  build: ../../
  volumes:
    - .:/app/examples/docker-asyncio:z

services:
  client:
    <<: *app
    depends_on:
      - rabbitmq
      - server_a
      - server_b
    command: >
      bash -c "cd examples/docker-asyncio &&
      pipenv sync &&
      wait-for-it rabbitmq:5672 -- pipenv run \
        python client.py \
          --n-clients 10 \
          --n-fields 133"

  server_a:
    <<: *app
    depends_on:
      - rabbitmq
    command: >
      bash -c "cd examples/docker-asyncio &&
      pipenv sync &&
      wait-for-it rabbitmq:5672 -- pipenv run \
        python server.py \
          --server-id a \
          --n-fields 133"

  server_b:
    <<: *app
    depends_on:
      - rabbitmq
    command: >
      bash -c "cd examples/docker-asyncio &&
      pipenv sync &&
      wait-for-it rabbitmq:5672 -- pipenv run \
        python server.py \
          --server-id b \
          --n-fields 133"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
